sudo: required

services:
  - docker

before_install:
  - docker build -t jasperkennis/client-tests -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jasperkennis/client-tests npm test

after_success:
  - docker build -t jasperkennis/multi-client ./client
  - docker build -t jasperkennis/multi-nginx ./nginx
  - docker build -t jasperkennis/multi-server ./server
  - docker build -t jasperkennis/multi-worker ./worker
